Add support for the Amazon Linux 2 AMI
and refine the code

diff --git a/supervisord b/supervisord
--- a/supervisord
+++ b/supervisord
@@ -1,52 +1,68 @@
 #!/bin/sh
 # Supervisor init.d script for Amazon Linux AMI.
 #
+# Originally forked from: https://gist.github.com/mhayes/866900
+#
 # chkconfig: 2345 80 20
-# description: Autostarts supervisord.
+# description: Bring up/down supervisord service.
+# processname: supervisord
 
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-supervisorctl="/usr/local/bin/supervisorctl"
-supervisord="/usr/local/bin/supervisord"
-conf="/etc/supervisord.conf"
-name="supervisord"
+NAME="supervisord"
+CONFIGFILE="/etc/$NAME.conf"
+PIDFILE="/tmp/$NAME.pid"
+SOCKETFILE="/tmp/supervisor.sock"
 
-[ -f $supervisord ] || exit 1
-[ -f $supervisorctl ] || exit 1
+DAEMON=$(which $NAME 2>/dev/null)
+[[ -z $DAEMON ]] && DAEMON="/usr/local/bin/$NAME"
 
-RETVAL=0
+SUPERVISORCTL=$(which supervisorctl 2>/dev/null)
+[[ -z $SUPERVISORCTL ]] && SUPERVISORCTL="/usr/local/bin/supervisorctl"
 
-start() {
-    printf "Starting $name: "
-    daemon "$supervisord" -c "$conf"
-    RETVAL=$?
+
+if [[ ! -x $DAEMON ]]; then
+    printf "$DAEMON: not found the command."
+    exit 255
+fi
+
+if [[ ! -x $SUPERVISORCTL ]]; then
+    printf "$SUPERVISORCTL: not found the command."
+    exit 255
+fi
+
+start () {
+    declare rc
+    printf "Starting $NAME: "
+    daemon "$DAEMON" -c "$CONFIGFILE"
+    rc=$?
     printf "\n"
-    return $RETVAL
+    return $rc
 }
 
-stop() {
-    printf "Stopping $name: "
-    $supervisorctl shutdown
-    RETVAL=$?
-    return $RETVAL
+stop () {
+    printf "Stopping $NAME: "
+    $SUPERVISORCTL shutdown
+    # make sure shutdown complete
+    while [[ 1 ]]; do
+        if [[ ! -f $PIDFILE && ! -S $SOCKETFILE ]]; then
+            break
+        fi
+    done
+}
+
+usage () {
+    printf "Usage: $0 {start|stop|status|restart}\n"
+    exit 255
 }
 
 case "$1" in
-    start)
-        start
-        ;;
-    stop)
-        stop
-        ;;
-    restart)
-        stop
-        start
-        ;;
-    status)
-        status "$supervisord"
-        RETVAL=$?
-        ;;
+    start) start ;;
+    stop) stop ;;
+    restart) stop; start ;;
+    status) status "$DAEMON" ;;
+    *) usage ;;
 esac
 
-exit $RETVAL
+exit
